apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "eligy1-deployment.labels" . | nindent 4 }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: eligy
  type: {{ .Values.service.type }}
